### PR TITLE
Tweaked departure countdown and added a category filter

### PR DESCRIPTION
**Pull request by rohit01**
Thanks for making the plugin.

### CODE REVIEW

**Comment by neuhausf** [comment]
It would be cool, if the category would allow a regex pattern.

**Comment by rohit01** [comment]
Yes true. Perhaps, we can do that later :-)

**Comment by neuhausf** [comment]
try my latest version to see if it works. the category-config accepts a regex string. if null, all categories are allowed (default).
https://github.com/neuhausf/lovelace-swiss-stationboard/commit/2ff8307868c355ce7511789adb5bd7c19be802e9

**Comment by rohit01** [comment]
Closing this, thanks

**Pull request closed without merging**
